apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: eck-operator
spec:
  interval: 1h
  chartRef:
    kind: HelmRepository
    name: elastic-repo
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 2
  values: {}