kind: Secret
apiVersion: v1
metadata:
    name: opensearch-envs
stringData:
    OPENSEARCH_INITIAL_ADMIN_PASSWORD: ENC[AES256_GCM,data:i7XQNfVekSfo34xG1ucMe5M0rlwc+0py,iv:smiltKfjHaKgtsuQryv6qNM6wCO7VBpsZGoY9EWw2Yg=,tag:O65Cl6CVNqSdfBJAgXr3PA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEcvTERKZyBBcFl5NjVn
            L29wcnZqaGEyNi9mbXRwQWU2T1RNNWhLVXFqTXBabnkrSUwzdAp4c2N1RXRQcVdU
            UjA0RW16elZMNnhKemlkUjJrU2FyUkhIeldKU0gwRjU4Ci0tLSB3K2ExdExzRE9H
            SEVyRFZSZlFkM2xnOVV5S05KeWVVQ2ZVK2dRUTZENlBZClYdjHuttJgKntrOjert
            1lcj/sqSYv4SmI0F8xK3B1OKBYuPYPkrR71vdEOIuK7PM8N1n6FZ9rqvP3mRd5Zc
            mT8=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qdmjd6g9zxszvw332nlw8898pl9q8tnpjv8ljjvxpau650567j5a6nlpjz8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IE1TL0VLZyBBbSt0azdY
            T0NJWDRwZlBRMmV1VTJjbjVBSEMwc3NtVHpxenI0TmVCd0ppRwpycko0eXY2MzZJ
            djl2SG5ESjdoa0R5L1VIQlNuYmlpVVl2VkIzM3FLcW8wCi0tLSAyd1QwdFQwbVdO
            UW5Yb2pwUU5EdjJ0V0F1UmpNdkk2WElITFlTNlM4QVcwCr7yJAeWPne3mbhkqzcd
            XcXiw914VOwHmlJ+XBRu019+CBkvuNoMXH+EHT4IRziaBcAqffiLlOdUjvU10cCq
            klU=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qwu0zwltgvjgv7tr0qcpjw6grreja8lqwpsxdprgwyap29mrkvx6j6795r0
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwNTVmaVhsSnNpbVNGRE5X
            QmZyRzZMcGR3OHRjekJRaFVYUDVLNDVmTEZBCkZJQmVOV05iZXdzSllCNGhnV3Bk
            dVNTNzg2QW0wcmhGUUZqb1dxd2dMTm8KLS0tIHZqUkZRQUhWenFQSm1LQlVzc3Fz
            VldtajI2K2EweTJJSXZiYUx0b1dOWEkK6WLxOJhL2Q8HwwHZ9bsPtA5VnFSH5yQZ
            8MiHlkKCCGEhFRa2PPnV7ANxfFUcEZZOBPEU3K8MyKJ81EHwrZcn3A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tufq3ztwqlaawpe4sd8pzh7t70fvgq8wwz7q0mka2rvrgvtngsgqhxay7r
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-27T03:29:38Z"
    mac: ENC[AES256_GCM,data:+CUgHIszaI3K6woQObIzF9t1y4xncga3CHXRNl66eE7v8266ShlaOPKfxiB0otRaUmFydPCnPRPouCpfqqVX8HPs8GKN1L+Sznirpu8JvE0UjSfO4qHapfPpRrAQPUfdGCXPIHAVCPKrhPwezHw4xoVLr45eIxrevpOYBeHtPuE=,iv:yh1eqftse0NNPakGubUNzBJwA9GUMZ50yJxzNN8+53w=,tag:fsIqkqcjh/Mch0N9uxqyfQ==,type:str]
    version: 3.13.3
