apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
stringData:
    api-token: ENC[AES256_GCM,data:sghhol27NgYslGPfG9dx1QSzC5Kb/NNGd7jU5fS1bdR/mn0xr+Pikg==,iv:kTPYM7Z4I6GdKAYiWk53gcHSMQJPrwVb4+KdmLIsR14=,tag:dXe9BX12RDSRZ7f7FjQNBQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEcvTERKZyBBeXU5Q0xt
            Q2ZWNTlpMmNTK3QyOHJGVVFCNllqVVpnQ3orV084TmhKMTJ3YwpueGc2QUYyU1hZ
            dEs0UFZ2a1RHNU1UZVpDVXo0OXJqSlgwempKeDQyaXNNCi0tLSBuOFIvbWNtK0lv
            aXpIN0hzV2VreTF4VlB2a0NzenBISFpXWExyYUgyRTJZCu9iYImCso0Au9fE/+yG
            ZbjrEq+FxvCfp7vvKxmDsHSICudZZFGKgLZ2c/jhA5jChxNGGyN9rdKSX0QWzDHf
            U+s=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qdmjd6g9zxszvw332nlw8898pl9q8tnpjv8ljjvxpau650567j5a6nlpjz8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IE1TL0VLZyBBNmJnVlFl
            OWc1VUNMS0JFM283bndhcHY2R3R3aGlCWithTGgzN2VtZnBXbwoxSEE4WTBPK2Yv
            eVgvNytOa2UyZU9zWktJZG0zTnNRTlVhdzRvQ2NVbGNjCi0tLSBhdlJEK2N1ZjBC
            VlZNeU5tVjJEdFpMaTgzRFVXY2lxK0svamQ0SzRuY1M0CqafsTt0H4E58ehpl2Co
            tn/eqba499KC52QQB9IxuKqntL7T3tccFsWdImi8DE0rHCfBH5wqTYgUASgYQAui
            a9w=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qwu0zwltgvjgv7tr0qcpjw6grreja8lqwpsxdprgwyap29mrkvx6j6795r0
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhWHRHU0NsLzFsbGlxbEFD
            aDhMVm9PNFArWVhuY3U4NG9aa2oyU2JXaXdNCkZ0NFFlamVJN3lyeEUyRkY2U1kx
            K2IrTVg2U1V3OUJlYWdLWjUwZWdtWWcKLS0tIFlxSDRVMXVVRTlHcC9mWm1YMkxF
            cC91MmFvR1RkekEvRnZuMUJ4cUFpSlUKg+nP8DcF2SIatUDaqNARWqN+vHtnNpDD
            Ri30l9CSv5wcaksl560xFQTq3JF8RH10Qbn01GaLHufNFTSOgpBazQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qx0rq7nr30zw7kjhlh5nccfj8w30hdnlc890c6hqxqack5eayevqm8wp8m
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-04T19:56:33Z"
    mac: ENC[AES256_GCM,data:vMDJvUqycKr6rda8HmXbbxCs6KcC4ODVsxSrnzJJ6Drx5ypt0L8jVrGn6M91bh40St4KSTAyFj0Pe3eKe7DkwqF8Qmk6ePgGHXZHQrOh6GfUI/QxnN8S01/KQHHF5a8jLEcGzH1JV2mMUwbHxzv6SYUVGQnGlEZIa9qXjRkv7OM=,iv:b4RccaDdzz6c594sibs9mdEnibSjoXiYcXtOxVLf7+0=,tag:lPXqNyp2K1mePh9iGd7xCA==,type:str]
    version: 3.13.3
