apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: disk-monitoring
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: disk-monitoring
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    global:
      alwaysAppendIdentifierToResourceName: true
    controllers:
      smart-exporter:
        enabled: true
        strategy: Recreate
        type: daemonset
        containers:
          main:
            image:
              repository: prometheuscommunity/smartctl-exporter
              tag: latest@sha256:4e61f74379c91ee832b9fa3e65e65e6a14ef436d3736cf83279e76208d17dd01
              pullPolicy: IfNotPresent

            ports:
              - name: "metrics"
                containerPort: 9633
            securityContext:
              # Hate this
              runAsUser: 0
              runAsGroup: 0
              privileged: true

      zfs-exporter:
        enabled: true
        strategy: Recreate
        type: daemonset
        containers:
          main:
            image:
              repository: ghcr.io/onemorebyte/zfs_exporter_talos
              tag: v2.4.1
              pullPolicy: IfNotPresent
            securityContext:
              privileged: true
            ports:
              - name: "metrics"
                containerPort: 9134
        pod:
          nodeSelector:
            zfs: yes

    podMonitor:
      smart-exporter:
        enabled: true
        controller:
          identifier: smart-exporter
        podMetricsEndpoints:
          - port: "metrics"
            relabelings:
              - sourceLabels: [ __meta_kubernetes_pod_node_name ]
                targetLabel: node
      zfs-exporter:
        enabled: true
        controller:
          identifier: zfs-exporter
        podMetricsEndpoints:
          - port: "metrics"
