apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: disk-monitoring
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: disk-monitoring
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    global:
      alwaysAppendIdentifierToResourceName: true
    controllers:
      smart-exporter:
        enabled: true
        strategy: Recreate
        type: daemonset
        containers:
          main:
            image:
              repository: prometheuscommunity/smartctl-exporter
              tag: 10.11.11-1
              pullPolicy: IfNotPresent

            securityContext:
              privileged: true

      zfs-exporter:
        enabled: true
        strategy: Recreate
        type: daemonset
        containers:
          main:
            image:
              repository: ghcr.io/onemorebyte/zfs_exporter_talos
              tag: v2.4.1
              pullPolicy: IfNotPresent
            securityContext:
              privileged: true
        pod:
          nodeSelector:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: zfs
                  operator: In
                  values:
                  - yes

    podMonitor:
      smart-exporter:
        enabled: true
        controller:
          identifier: smart-exporter
        podMetricsEndpoints:
          - port: 9633
      zfs-exporter:
        enabled: true
        controller:
          identifier: zfs-exporter
        podMetricsEndpoints:
          - port: 9134
