apiVersion: v1
kind: Secret
metadata:
    name: grafana-filerealm-secret
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:UQizWXYYP1DRTNbDa34=,iv:OpqIKJJfZhLA+RMcYPZRM35M6X6DgxihVANHBs8vzkk=,tag:5DiyT01ATLHUndqklcWY9A==,type:str]
    password: ENC[AES256_GCM,data:BNuAX8x4LeDauwsU8IWtb5nfZp7HudmYUI61echtQxk9Uep20wFNLg==,iv:6BihQrHolJaqdL27TkpW5w3Gmnvud1mTKT1bdRVzl18=,tag:2aR2ynDGwN+w6hL2jh06Ag==,type:str]
    roles: ENC[AES256_GCM,data:tcB2Tsev,iv:LAL7Lq9FjFP88gE2s+R04Q8A5g4tghcC6OLGRNk5qv8=,tag:C95TAN3g1Z8rSP4dL0Goyg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEcvTERKZyBBeGVldnJj
            SWhocUVxUXNza2p6UlRjWEhmRDd3Tjl3SDh6T1RWWXF0a2dGYQpqSEVLc1hoUTN4
            WDhWMS9ZWWZybUdQOVRNWWk4K1pOZ3M1dkZyek9Zd1hRCi0tLSArQ0ZrNE9wU0Zt
            dytFQklKRkVlYkVZRXFManRZcTl4RXMyZTFQN3ZGVjFZCpPMDgovMCUYiW4SQ0fm
            R3Q51uosHEr+YiK0zbd+476SKIRii11xK1TIJruEdYmPm7aJspAEyUxWEY/3/eii
            n00=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qdmjd6g9zxszvw332nlw8898pl9q8tnpjv8ljjvxpau650567j5a6nlpjz8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IE1TL0VLZyBBNzh4Yysy
            WTdpTlA0Z2c3bW5Xd3lYNjVxL3RpRFcra0kyVzRGL0R2MWdpZQpMOG81QlB2ajMy
            UlEyUFlLbkE3R2w5S0gxVUI4NisyRDhGc2loc25vemc4Ci0tLSBFdCtidFNhcWdQ
            ZVozWmNrcVNCamNibGJTWDRUOE5kODAwb0lCZGJGYnljCmP4YMJY/gHRw08XGwJg
            X7SVITvg4rmKW6TYesnAihPMef4gJ6fdzgywhqCJ+jDNhnHS+j+7PBpKE7K8dzvd
            /MY=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qwu0zwltgvjgv7tr0qcpjw6grreja8lqwpsxdprgwyap29mrkvx6j6795r0
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDTW9Ia0VjQTBMSXI2MFlV
            Q3hJZXZlMkZwODYvSFcwYnFzMnZRZkRiKzFnCk84ODNwNzBINUlqVU1WbmpZbkor
            dy9zUERVaDRUdU15MDVvNFhISExYQjQKLS0tIGQ3VmR1clNpWDZSaTZDeHhqaFph
            VFI2VmVBL3hxRHRaSXM0b3M0V1J1bmMKlAJXcbXh+qbQgeKwjjFqSe6McNLAx0BH
            TYLW7NKDHaZj+ZzvZek8KxS6+YAXa4pS2/Hw+ccYTKF/NiByombqQA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tufq3ztwqlaawpe4sd8pzh7t70fvgq8wwz7q0mka2rvrgvtngsgqhxay7r
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-28T20:25:35Z"
    mac: ENC[AES256_GCM,data:HzkCyZqsaERNu1G3Se/hpAmQSezCBysMO+EDEVDzCGw1uVFJQVsYzP/ZzXJ7i+XWkcwkmJRRHpZFJtKM5nIS1OO7GMS19ibb98WdlZK/QgpWhC6aBkfjHiU4qDtYQ2eCRqSb6t8P6998afxjG31mgWPJ5wCx4/fOIj9t8pBwgpM=,iv:EH/hVGAOoAbr9HqAoiE7wo2mlAqAI/+npFdjkR7Hzpg=,tag:DmQHoQE6MZ54duUa7q0q/g==,type:str]
    version: 3.13.3
