apiVersion: v1
kind: Secret
metadata:
    name: vector-filerealm-secret
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:Zv1EA0DS,iv:ArFGFFq93yDdzSntLGgYmeXMt/X8u9dRy2inKi/TFyQ=,tag:CqKtcIBgFOlr3J7BPwb3GQ==,type:str]
    password: ENC[AES256_GCM,data:eGjEAjJNa4EIsRvLUknb6n3WlU8FGralC8f15s+QFSHo1xY9jKk3QA==,iv:1oDARo14bxqRvWrF5qXEb/BuWTp9qrdf85Hz/Sv4gOU=,tag:w6CAf616nP5/enJNk3/tNA==,type:str]
    roles: ENC[AES256_GCM,data:MwuZgNQStnWgeHQy,iv:GjppHCcyd5+Etyf85ME+uxcloIblxmuqWvnPYKO74zw=,tag:SMCUkHeukFWynFLcYcDiuw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEcvTERKZyBBdEp2WkFI
            VGV2TnA0eThBNkFJaUxBR3ZackZUM0tJZHhxTjl4ajVZSVlTOQpNSldtUnROR1hK
            cENOaE9RYytGb2xQNU9YayswQlovdXNGeWVRSFVXTWFJCi0tLSBHcHB0UEx2VHd2
            ZnRSb2lPTENUYXVRUXhaeWtCMWdXZURlVUhteU5SVkR3CnWyKwOI7Obn9aQrHI4O
            AavXOKYOB+DshCdMd0d3GrORXZGeA29xobLPVAp1M4Z5IIc8DLjw7jOiSpe9Pjl2
            jVE=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qdmjd6g9zxszvw332nlw8898pl9q8tnpjv8ljjvxpau650567j5a6nlpjz8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IE1TL0VLZyBBNUVabmlH
            R2Nyc00rZ1VqN2Z5cGU5dHpFdTVob1NPNDJDd0RGdERKcEgrWQpQL3FlRERLN0Zh
            MEllS041MDZUVWQ2RnEvaVFxOWhwY0RpR3dOSk9TTC8wCi0tLSBXOVVsYk9wR3B0
            VmRBTFp4OWkwTWMzY0l6aU84cFhTQ1BMc0l2N0FqQnpNCprqNQx/qT8XMPB+Lyl/
            OCfML7/nRK9PQegdxBul+G2se7RKZTMNfUdwN3ZO14dPdXfSMemkDlqlQuFKEyZe
            9HU=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qwu0zwltgvjgv7tr0qcpjw6grreja8lqwpsxdprgwyap29mrkvx6j6795r0
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0QkkrbmFEL1ZtQUh5eWRG
            dnFyWVNzZy9mYkN3a2ZHUTF1bFhLSjc3T0FJCktXenZ3UjV2YkRYVkJDQ3RWT3Az
            UHZ5Q29zdHhhNFNyQ29tMkxQM1RtODgKLS0tIG1KOU8wdTlUalFSbUQrTk12eCtO
            MWMrY2tjUWgrSDNnWnBYSWZ1OTVIdWMKvnrEqG9hwNTzClzzCusqJL0I31rHmSXn
            SF6LKU8h5jWzVg0XbI0kiVmeZtuekQcsNXYfD8Qbll0fYN2MpyD9MA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tufq3ztwqlaawpe4sd8pzh7t70fvgq8wwz7q0mka2rvrgvtngsgqhxay7r
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-28T20:25:39Z"
    mac: ENC[AES256_GCM,data:kClD+eBbH+l70YerizTscP62KNW3n93TMeS7o+JF9WEQucFLmYnXu9MYoy1aLvIGUQPAi/y5d/ugLMG4M+2xc5ehFXnYkQ8vGVmuYjMTQb95xCohFSTMvu/vCfrFG2CpbCIIEUCPFuC4j4zshJN6hEtUrFmk2LbaokLuuMS4iZU=,iv:BSx/qVv+GQEqrw4cvUvDl7+Tbe3qZvuWTtYzsn8U0ms=,tag:NPv+oBCJ1wzkg5P+EEdvhA==,type:str]
    version: 3.13.3
