apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vllm
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: vllm
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    global:
      alwaysAppendIdentifierToResourceName: true
    controllers:
      main:
        containers:
          main:
            image:
              repository: docker.io/vllm/vllm-openai-xpu
              tag: v0.27.1
              pullPolicy: IfNotPresent
            env:
              HF_TOKEN:
                secretKeyRef:
                  name: huggingface
                  key: token
              AUTH_API_KEY:
                secretKeyRef:
                  name: auth-token
                  key: token
              MODEL: "OpenVINO/gemma-4-E2B-it-int4-ov"
            command: ["/bin/sh", "-c"]
            args: [
                "vllm serve $MODEL --trust-remote-code --max-model-len 8192"
            ]
            securityContext:
              privileged: true

    defaultPodOptions:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - bulk-datastore

    service:
      main:
        controller: main
        enabled: true
        type: LoadBalancer
        ports:
          http:
            port: 8000

    route:
      main:
        kind: HTTPRoute
        parentRefs:
          - name: "internal"
            namespace: "gateway-svcs"
            sectionName: websecure-gw
        hostnames:
          - "ai.jsck.network"
        rules:
          - name: "default"
            backendRefs:
              - identifier: main
                port: 8800
            matches:
              - path:
                  value: /
                  type: PathPrefix

    persistence:
      config:
        enabled: false
        type: emptyDir

      model-cache:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 100Gi
        advancedMounts:
          main:
            main:
              - path: /root/.cache/huggingface