apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: traefik
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    additionalArguments:
      - --serverstransport.insecureskipverify=true

    ports:
      web:
        proxyProtocol:
          trustedIPs:
            - 192.168.0.0/24
            - 10.0.0.0/8

      websecure:
        proxyProtocol:
          trustedIPs:
            - 192.168.0.0/24
            - 10.0.0.0/8

    providers:
      kubernetesIngress:
        publishedService:
          enabled: true
        allowEmptyServices: true
        allowExternalNameServices: true
      kubernetesCRD:
        enabled: true
        allowCrossNamespace: true
        allowEmptyServices: true
        allowExternalNameServices: true
    deployment:
      annotations: {}
    securityContext:
      securityContext:
        seccompProfile:
          type: "RuntimeDefault"
    experimental:
      plugins: {}
      kubernetesGateway:
        enabled: false
        gateway:
          enabled: true

    ingressRoute:
      dashboard:
        enabled: false
      healthcheack:
        enabled: false
    tracing: {}

