kind: Secret
apiVersion: v1
metadata:
    name: habor-inital-password
stringData:
    HARBOR_ADMIN_PASSWORD: ENC[AES256_GCM,data:W4cWnIcNUGcgP1uR+hu6H3EB3ARBdigr6V/lRUOPudGZrCVLDg==,iv:K+BJbD8Yn+7UFZIVRUAvO9TdlrxtvusCPhpODx9MYBg=,tag:It+ODlS6vxu3lPm4pHYBwA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEcvTERKZyBBdWxhMTJ6
            YVJvTnNYZ1d1OWVQK0FQZi9KUGYxQnYzUHVxWFRvT2J5ZmZ3Ugo4RzgzMFdCQTZU
            S2dzQTE1ZzFvdDRZY1I1azFGbHArTTV2dHNBbUVKZkpnCi0tLSBhMXpSMVN6TFh6
            OWtnb0plR01YRGUvSWR0QjZSVlNMRkZaQUN3S2ZtRHVFCgr4s4rP2siVZbw3KU6v
            k0TN2S9HjxdPg/nwPJZCl/Fv6fFvwvHAGVyKuj3zgjsdtfkjyrro+xZeGt+qbsYQ
            JhI=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qdmjd6g9zxszvw332nlw8898pl9q8tnpjv8ljjvxpau650567j5a6nlpjz8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IE1TL0VLZyBBbVR5VFJE
            bWFiOHhzTmk5cUlaNDhUOVpaRmRXZmRZSjZQemVZZEpmS09hTApKRWYxQ2NsZ29k
            NlBCVnhwblpFbVR1aVlUL21UUFo3OEJLOHdlSTNnOWp3Ci0tLSBCd3NWdnhXanhp
            ZE5jQ3UyT0U4elptRXVUM0Y1S2ZzR2ZDb2hTYmdpNkFnChJewVD5XWC48Qq9+dZQ
            NMOMnYLXR7Qk1M94005GLm1I05iqneVLYZUR4mv6c2DIwzBHcSeppjKeaEZQEQWQ
            l7s=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qwu0zwltgvjgv7tr0qcpjw6grreja8lqwpsxdprgwyap29mrkvx6j6795r0
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBURmtib2l5VFEwa052YmVh
            djc2K3c5L2JBWitjY0kwa2gwSnd5enlSOUhZCmJPbUxlbFdXanltVTIrK2JxcExv
            ZnRGV213VURNOVFRUGZGdjFDTVVtZWcKLS0tIDM4RmhLS1BvN1VtczVMcTFRTUlO
            aVAvb08zT3NFNkxLcE5VaTFxaGROZHMKfGKj5EsFbwTkf+IhPeKvXdNK3bFUczzp
            18iSH/+NqQq51/iaeIOc5F6UYVl/orbMF/E+uelCzw0tXwrM20mDtw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qx0rq7nr30zw7kjhlh5nccfj8w30hdnlc890c6hqxqack5eayevqm8wp8m
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-04T22:48:21Z"
    mac: ENC[AES256_GCM,data:Kfuha55Ki3ngdQh1Qpz0B+2dhf2OrdK6AJWp7p+uuTwcMDHYui6Q+eNpI/vU5PczM2C0h0QWuTcDdhEVQM/Zx8PCkPvLm4IQtsQBCnUml3av3df+AGJxa892UlSTDlstBI5EOk/qFgzITF0JfL7MjTft3inEnhh8m/z6pzG/MeE=,iv:40WrCwJQ/uiZls2aUYjkrJiYx8N8DwoZkJHsshgZ+TU=,tag:Qla44vOh2ZP0hAHwmRkTjA==,type:str]
    version: 3.13.3
