apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor
spec:
  interval: 1h
  chart:
    spec:
      chart: harbor
      version:  1.19.2
      sourceRef:
        kind: HelmRepository
        name: harbor-repo
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    enableMigrateHelmHook: true

    ipFamily:
      ipv6:
        enabled: false

    expose:
      type: route
      route:
        parentRefs:
          - name: "internal"
            namespace: "gateway-svcs"
            sectionName: websecure-gw
        hosts:
          - "harbor.jsck.network"

    externalURL: https://harbor.jsck.network

    portal:
      image:
        repository: docker.io/goharbor/harbor-portal
        tag: dev-arm64

    core:
      image:
        repository: docker.io/goharbor/harbor-core
        tag: dev-arm64

    jobservice:
      image:
        repository: docker.io/goharbor/harbor-jobservice
        tag: dev-arm64

    registry:
      registry:
        image:
          repository: docker.io/goharbor/registry-photon
          tag: dev-arm64
      controller:
        image:
          repository: docker.io/goharbor/harbor-registryctl
          tag: dev-arm64

    trivy:
      # enabled the flag to enable Trivy scanner
      enabled: true
      image:
        # repository the repository for Trivy adapter image
        repository: docker.io/goharbor/trivy-adapter-photon
        # tag the tag for Trivy adapter image
        tag: dev-arm64

    database:
      type: external
      external:
        host: "harbor-pg-cluster-rw"
        username: "harbor"
        existingSecret: harbor-db-secret

    redis:
      type: external
      external:
        addr: "harbor-valkey:6379"

    persistence:
      enabled: true

      registry:
        size: 256Gi

      imageChartStorage:
        type: filesystem
