apiVersion: v1
kind: Secret
metadata:
    name: harbor-db-secret
stringData:
    password: ENC[AES256_GCM,data:WYKBkclXkn47J+cSsahJo6iBegHuZ1B+jYhs/g2Cqup8,iv:+lZ7QJm6riyc0dd+obkYHTpJ33skdX4AheJF6o0eg8c=,tag:c7gs579zJQyC0fSRqFrzhg==,type:str]
    username: ENC[AES256_GCM,data:LUHDNZQh,iv:n45SpvvhEpJ8r889jtJ0hE5W3v/dBQ/DIg3//NoTiW0=,tag:OmAjfpxo4q8TlinVrDIw2w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEcvTERKZyBBdjNGZWh2
            TzVIRExoMy9iWXlCaW14aVJWVnBJa3psQmphZG9xMkNFQVF4RQpiVTB1U3NLaTVC
            RWk0bVp1QmNXQzFPekt4a2pRblJ0dWZyUHdseHN2MlFjCi0tLSBjZzFwODZoNThN
            cjlNV1hhV3ZDWXhpZXdLLzA5U3FDaGFnWFNGZzZyK2s4CkvSCst6bgJ7NmUKf75z
            QoV/1ngP4l3X/592BTbY6GC05YRsUE1Glh1Ji89kYXHBOt/SfNruWZT26Anecbmr
            tF0=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qdmjd6g9zxszvw332nlw8898pl9q8tnpjv8ljjvxpau650567j5a6nlpjz8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IE1TL0VLZyBBeUU4bWpC
            a2ZOcGcydSt2cUprNkZBRGlKb1AyUy8yekdrQ0ZDdk5QdjFETAp2VTVOZWZwUUdH
            V3dJSDFaUkVnN1hrdTh6dzFYUkdCNk5ocENWQkE2Z0FzCi0tLSAxZ0wzYXRpdmg4
            bzk1a0owM3JZM1lhcXBXWG5GRS92cWZ2cTR6T1BjTTMwCqzy6FdR+Sg9Fevnhp6H
            RGBzEgN+TnN1R8a2lWe+YI3g89epcVuxHZWgomMqtQ9ly0d1sFlApH9CTvkMWaKA
            V9A=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qwu0zwltgvjgv7tr0qcpjw6grreja8lqwpsxdprgwyap29mrkvx6j6795r0
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaaWlNdmZ4QTBDVXFYWUQ2
            eU42a2tMU0N4MkFZT1o0RVBXeGxOYjg0bVRnCjVNcU9IK2x1eU5BdWl0VVgxTE5J
            UTVYMGhEVm9ob1hiSWlLYVljSm1zNlEKLS0tIFhqTzhLWHNqRkh1a3VCUDRCSUo4
            OSsrRnU4dVdsSmo1L2RlTGFLNmc2dXcKkIurKzL2qlH+yEWpUdWkyGjeyuYZaPLi
            l9HbP8T9ACRcJsR6yk26DzMlWw254pZvEyHifktBI8QecY6KSoSASg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qx0rq7nr30zw7kjhlh5nccfj8w30hdnlc890c6hqxqack5eayevqm8wp8m
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-04T20:02:42Z"
    mac: ENC[AES256_GCM,data:6/ATHTjFviBPpgtHrdzxMqErQvqEFwgtSt8xJhkFYHxPWV50HQj6FROFTe3AAk/Fny5/+SSEf6Y+1paYRK415NXuN1q1fJF6ipb5OH5e0LB7H83uDfEIc9AeYuliPbq50MDkQ8aN+uY2Be81vJKoQkSQo5fJsLb7Q0QYYWXaprI=,iv:M7zeSkt3dMV+XSIVVFt7DV3vVABf2e+UyblPk4poefc=,tag:p4itjkHIlI8tEpgiF9u2Sg==,type:str]
    version: 3.13.3
