apiVersion: v1
kind: Secret
metadata:
    name: unifi-dns-secret
type: Opaque
stringData:
    UNIFI_API_KEY: ENC[AES256_GCM,data:53VDAB7/QbDkjlCLcKForZIunxQMpRedca7y6MxUGmw=,iv:139cPDhnHrHEcUH9PuHSL8TlncdQpxrFa0fZl0eXRUU=,tag:vKbn1eTuVCOc5gpV3S+bTg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEcvTERKZyBBM0NtSUtw
            dXVJZ3Ard1NzdXdEYlpXRUJuOUVGZ0tiMHpqTEw1U0VsaU1pbAorT2NXNDU1MXZ4
            d0YvNDIzWTNOWU5rRGRpYUlUS0ZRMzhJTS84YnVRM3Q0Ci0tLSBxZk9Xcm5qS3Bj
            cDJyeVV5aCtXdXJLOTMwN2FOdEpEVWxEOWg3TjV1MG04CjDknA9AkbUKj+QYgwas
            RKJkAk1gcsY60ehvuWunI9cKuGKti69dczakThpahExe48uiVNNchXnqbzqpHCiE
            CVk=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qdmjd6g9zxszvw332nlw8898pl9q8tnpjv8ljjvxpau650567j5a6nlpjz8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IE1TL0VLZyBBb3Y3b2NP
            NzBoRmdrb0UwT1NFY0prUFNHSWRmZ0NKc3lBVUQ4aXBUUTU3Zwo3OUdMVkJJU0t2
            bVFvY1IxeDVuRGdidE81WGE3VkVEaVYwQ2J2YWRlbVR3Ci0tLSBUcEhWTkd0MEN2
            OWFOTEhDdUM4MlZmakc1aERpU0ZYNDJRaHdvUExyeUN3CpwwpDL2oLP3iZh795qh
            Ub7fyBqp1L7Y7y+K2M0XgBjK+K/MI/h5K9ZICoUcI8bpO6TpTi7Qoqnb5UgzHDgy
            sMI=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qwu0zwltgvjgv7tr0qcpjw6grreja8lqwpsxdprgwyap29mrkvx6j6795r0
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvYUp5U0JDV2Y5dGJxRzFi
            RnRrWGdKMHoyU0xBdll1aUFxNmxpNWx3aGo4CktyZXQ3SlFKT05xeGNZYXpzQWd4
            cVdXQXpkQlNkZlBzVjFUdFU3YWpja3cKLS0tIHpGQUUxdDVKdkVBWnZ0TXBBODZs
            NlY2WTY4ZW9CSHdjcWVvZnpIcDBuYjgKF0krP70looRaiAeFuvKiR9NyykcV6w29
            14ozDCJsTivQb72+5qjx3V57DQ4IamvduIr1gy5X7T7m/QVN86bXBg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qx0rq7nr30zw7kjhlh5nccfj8w30hdnlc890c6hqxqack5eayevqm8wp8m
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-04T19:56:53Z"
    mac: ENC[AES256_GCM,data:d6ltFPuwltA+A3HY7vcW9SoLK1UM3quL27RglYmzFMEWIyvyFvFLF1sWgGtuMJ7KR7jDn6jW9/CN7CXPQ4KFFyHjVKa7B7q2aPlU1dLUK77KSzP0tyIdBt2VG3UnqJ3mZJF3OsUGSJvG37/Eo0nZ2sgx0S9p6QlBY8+F1loT9dI=,iv:N5Cxzje2/tltChlMv5UBv4TsBxllbz64JDVEumnKBmY=,tag:1xWkmu+/JVQMjug+tOIV5w==,type:str]
    version: 3.13.3
