clusterName: falinks
talosVersion: "v1.12.6"
kubernetesVersion: 1.35.0
endpoint: "https://kube.falinks.jsck.network:6443"
allowSchedulingOnMasters: true
clusterPodNets:
  - 10.244.0.0/16
clusterSvcNets:
  - 10.96.0.0/12
additionalApiServerCertSans:
  - kube.falinks.jsck.network

cniConfig:
  name: none

patches:
  - |-
    cluster:
      proxy:
        disabled: true

    machine:
      kubelet:    
      # Give cilium a route to our dns server
      network:
        interfaces:
          - interface: lo
            addresses:
              - 169.254.116.108/32

controlPlane:
  schematic:
    overlay:
      name: rpi_5
      image: siderolabs/sbc-raspberrypi
      options:
        configTxt: |
          gpu_mem=32
          kernel=u-boot.bin
          arm_64bit=1
          arm_boost=1
          enable_uart=0
          dtoverlay=disable-bt
          dtoverlay=disable-wifi
          avoid_warnings=2
          usb_max_current_enable=1
    customization:
      systemExtensions:
        officialExtensions:
          - siderolabs/nvme-cli
          - siderolabs/util-linux-tools

nodes:
  - hostname: theroom
    ipAddress: 192.168.13.250
    installDisk: /dev/mmcblk0
    controlPlane: true
    nodeLabels:
      nutty: "no"
      zigbee: "no"
    volumes:
      - name: EPHEMERAL
        provisioning:
          diskSelector:
            match: disk.transport == "nvme"
          minSize: 100GiB
          maxSize: 100GiB
    userVolumes:
      - name: persistent-data
        volumeType: partition
        provisioning:
          minSize: 100Gib
          grow: true
          diskSelector:
            match: disk.transport == "nvme"
  - hostname: house
    ipAddress: 192.168.13.67
    installDisk: /dev/mmcblk0
    controlPlane: false
    nodeLabels:
      nutty: "yes"
      zigbee: "yes"
    volumes:
      - name: EPHEMERAL
        provisioning:
          diskSelector:
            match: disk.transport == "nvme"
          minSize: 100GiB
          maxSize: 100GiB
    userVolumes:
      - name: persistent-data
        volumeType: partition
        provisioning:
          minSize: 100Gib
          grow: true
          diskSelector:
            match: disk.transport == "nvme"

  - hostname: brightburn
    ipAddress: 192.168.13.69
    installDisk: /dev/mmcblk0
    controlPlane: false
    nodeLabels:
      nutty: "no"
      zigbee: "no"
    volumes:
      - name: EPHEMERAL
        provisioning:
          diskSelector:
            match: disk.transport == "usb"
          minSize: 100GiB
          maxSize: 100GiB
    userVolumes:
      - name: persistent-data
        volumeType: partition
        provisioning:
          minSize: 100Gib
          grow: true
          diskSelector:
            match: disk.transport == "usb"
