apiVersion: v1
kind: Secret
metadata:
    name: jellyfin-db-secret
stringData:
    password: ENC[AES256_GCM,data:Jq9OI6Ne8UZCUegt01L5wACWdnmeK6PilYNY/C6/e1Q=,iv:jQ+JmQB2aN/R3txndFjpVHTMZG4C2WCZzQxFkBX/Tx4=,tag:VVpXW2bH1rIaDG6ipZAm+g==,type:str]
    username: ENC[AES256_GCM,data:mAJq+O3TukY=,iv:i1yrMxMGKlUjGgqLE16toisNYDnmyooPuv6bGdYKggU=,tag:pJlqAef7ESH5jhjxtrx8Gw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEcvTERKZyBBbXVzNFBm
            RHExWjVaV3hQR0oxakFyaE9VODRrWCs4bmpGTU00QldGOHJmeQpFdEppbHRwUDF3
            eERXYVJTUldJeDFySHhqa01RVnJCbDNocEcybHhodnZZCi0tLSBHdWI3NVkrVU9T
            Z3NmOEdWcG1NMWFZWXZ6eitWZG9RMXdraEx3ZUNqaktFCgm8JsMLZrz+4kx8/WG2
            BZQ0K4Sfh9a+R04vJ2G4KJsxrbxvzjOzlkNsggPdeK5uun0hTa6i4xa/7as4PYQk
            37g=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qdmjd6g9zxszvw332nlw8898pl9q8tnpjv8ljjvxpau650567j5a6nlpjz8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IE1TL0VLZyBBaW9YZlhh
            WitqNG03RnovU0xDdXlWc1lCU2ptM0JhUllUWnUyenhUOXFxaQpnbTV4WTdsOERM
            MG5DeXhubWgxL3NJckNTazJsRUxyNnFnNXVlbWlsWHA0Ci0tLSBpQlFwaTBZZW8r
            QVVDNUUzZGFBbVZFTndieS9yZU1QT2Z1SWVzTWtXVFI4CmzfXPxhjYn0MvkpWPPR
            9i6SX3yYYJ0RsTb/dn1NqANkt54ZLHnEX3gQrWy091am4W9vqV3GSP53UF31R3kv
            p10=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qwu0zwltgvjgv7tr0qcpjw6grreja8lqwpsxdprgwyap29mrkvx6j6795r0
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3T3R3dUpyWDJjbzY1dVRY
            aUxqQ1RId1RXMnZLRWF0QktVSGJKRURFc1M0CjFQdHdNQ2VuMlY3KzVRRXI0dkRj
            Q3grR1hVVC9VZVkyZndLTTBCT1hBeGcKLS0tIEJzUDJoalRtTmVsdUQyL2NUdENY
            YTJjUnJHdm5IWVZJeUtmMzZBZ0xFQW8KyHjJKv4iYb9+kohtMXcnDqTusoibFAh6
            oNtaLteOQLXqzJTQv2DfolZ6OpcpAwC9XKmfKJ9dE5QH5+wO1yhsnA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tufq3ztwqlaawpe4sd8pzh7t70fvgq8wwz7q0mka2rvrgvtngsgqhxay7r
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-08T02:27:46Z"
    mac: ENC[AES256_GCM,data:vphn6J0DPoLEeD7PLxngXlnZh2FUh9Q9rEROn+ZvqNiu2VRI74xBF05VSFBAG7HP+nE3j4g5ckpzm0TZVNAEPlaBGzsQw/kin8WZYpv2veLWEq+8Yoo6RZGH2yLAMZ2jU+RDsbYHqa1PmIKgf0a2ZWucXZ0HXE/O2w2/ktz9N8c=,iv:viQY+9yvNE8kF/KoEi41z7+AiWKvMKOVrFqGqMmAkV4=,tag:GGYiRCDHuoLWSKSTQ/1IEA==,type:str]
    version: 3.13.1
