apiVersion: v1
kind: Secret
metadata:
    name: unifi-dns-secret
type: Opaque
stringData:
    UNIFI_API_KEY: ENC[AES256_GCM,data:OJLceAwiAsvoCSMxhxqDEeFZiBAFTfeBgdnPLPi1Daw=,iv:n806UuwKaY2PTeX8EDlA41Rg4fgL06WtjMBT7e7PnBk=,tag:7klbpbd3mDOxZoZVtduXeg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEcvTERKZyBBZ3M3dHNn
            K0hHUk0vSTVMWkpJNk1KNVY0MGtJbnE0TXNCQXFxZW1FNnU3QgpEeGZJOTdORUZ3
            WFNDaGlIY1MyQjdUQ2NNMzJuNmc4ejNBek9UWnB5eVM4Ci0tLSB4UTJPUnhOUXVz
            LytVeU56YVVRQmc4WTZEU1JGYUEyekJYLzVDYzZ3WENFChhFi+V+BurOTno3ZNbx
            hJqxZI9yZ27oDXsdEMVk7Uoo6UirlRdk7F3jDJD/eTogF/RWSyaemeseXhpF33HK
            RIM=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qdmjd6g9zxszvw332nlw8898pl9q8tnpjv8ljjvxpau650567j5a6nlpjz8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IE1TL0VLZyBBM0tnQ1Nl
            YmdHMTc4d2RFV1o1T3lRcXRlQ2dIQ1NyVWxRV2VjV1lRZEpzKwpkSGgxWHU1dWxF
            aitqNE4wZElCU1hQU083SlV6aG4xdmF0dlBWNnp5dzNjCi0tLSBHZGhYTnF5c3NE
            ZjNnYVUyVzlTTU9Pb1FjSEpZbGRoRUNXSlBEZm5jMm1VClrEiVzVpsfvXTOVKwSk
            C8v6hH4XrBaGcVDSkN5oC4O5LqNKTHO/nhxpAICMCPj6AvnTtglmH1DMP5/Vmsg2
            t7Y=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qwu0zwltgvjgv7tr0qcpjw6grreja8lqwpsxdprgwyap29mrkvx6j6795r0
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBub0tZRHRwL1pvQ01KZlNv
            cm1VOStDdkpWdnczSzVncURrcUFtUUViSkFFCkM0VDFGYms2MHorZTBJNXplcFJq
            NEhGVmtQQVE3MnBFZVNKeGl5dEZ6MG8KLS0tIHRtVVNHNUVublhMUThRUHFLRm5J
            L1VndGt2bWlkQWQxVkVkL042NGhjYmcK1SKtUCpKdR5Ks/I6I9RDKmGv8+NDOyZO
            myk6BMq+MgK1RhAqipcImCnDm44iTcoskxoQpe1RbJA52iyrozFIwA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tufq3ztwqlaawpe4sd8pzh7t70fvgq8wwz7q0mka2rvrgvtngsgqhxay7r
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-30T14:05:36Z"
    mac: ENC[AES256_GCM,data:iH16JlLaps9fP5LQiwy6rvOrXzkf/M7QjMbzBOPOMaq1aD8q+h9GLuKLC0KbkhSIHvcn0IK4d6+C5UKM5vdqY7srfXceejt9UPe7QrwQrRj7q7XTNa70LpN7h7Te7P2cXrCFzJaSHmSM0tjr3KwhbWznRDefCFC5NzQWwEByQBk=,iv:kV5I8Uwz9LLIFatftBnUiJpr3JWV3Yzxx+71e5BL97s=,tag:Tf8GixdPYkNQHgs8egaLeg==,type:str]
    version: 3.13.1
