kind: Secret
apiVersion: apps/v1
metadata:
    name: grafana-client-secret
stringData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:iCbHPdg+/MyjeaQKn+i2He4N0XHyOvHRE/bO/pDZXSdP6Irmc0w3RWieKYrrDUSi/0A9FOQlRULYVVgwCd4iOFsuTvy626hrr9vPjbr4xXRHttQuZOHn1MDrwa9nQsw1tNpgJUQNB040MoZYU5/HGCP0jYOvcev/5jkTSlmt1sE=,iv:MH3twi1IoENlri+BRFn3Z8xtxwDfyXTUsguGbshxTi0=,tag:FVIIfNLomPJGu94Re7ILdg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEcvTERKZyBBckpkcHpR
            cmVRQWpzSUdrdXpzWHlPZTE5R2swandyVjQ2TEpjRHBSaEw4WgpoS0pQeUozZEJv
            ZTYyWU5xZTFtRUcra3ZUUXZKc2Z3MnplaTQ3WVBWdXJzCi0tLSBsRlNoWVNxSWh5
            Ym1nQXBmR0E3dk4rMUY3Uk5MNUovQjRiclFQQ1dueVIwCkvwTLynnPh2gj4Z/wRo
            yT5eLkPS0zew70w8pmLTiZF1+MUytBa9sU0eLDT4LPR8BnK8nWQLrFdQCyZ/zgdB
            baE=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qdmjd6g9zxszvw332nlw8898pl9q8tnpjv8ljjvxpau650567j5a6nlpjz8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IE1TL0VLZyBBM3FtMTFk
            SFNCUTdyc3c3bGJkVEFIT3I4VHN4c2RXL0NvR1VLVEZFN2tiVQpaNWE4TWdYdUhJ
            VXVsb1Y1V2NzampSKzRNSWZkQ3VUOFdCRzg0RDQzWk53Ci0tLSBDbWxLNkt4L0ZF
            UjFRL2Mrd0F1eHJVZ08wTElrOHY3dklZbU10UzN2NnBVCq9hiUY6bTcgkHICOemN
            AgTQy5v435bzBkPZOWOpsQNR+ELE0zESALfqe8nN8G6DSddIHdyHWSfW4ZbEazan
            cKU=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qwu0zwltgvjgv7tr0qcpjw6grreja8lqwpsxdprgwyap29mrkvx6j6795r0
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkUlFCaXY3bVRycWhkKzI3
            eGxxUFZpZy9MOVY4dU1CSXVhNHEycjZjUEhjCk1QNk9maUdWWFdyRS9Yb1R1VHY1
            K2xTTVBOZ0UrSXo3NEFvNzRYakFjTzgKLS0tIFBOZkJiYlVKN3hnY2tnd0lObnQ5
            a3hObGR6dUJKcjhzM2p1VHNhNXdWS0EKpAQ1qB30K3cejEQ+hWa30XxC6UMS1W4q
            P2kcue5Bf1M0CxOiop1Edm0ToBXrCCtLwiSP80I3+RI0lKHThhZJIA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tufq3ztwqlaawpe4sd8pzh7t70fvgq8wwz7q0mka2rvrgvtngsgqhxay7r
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-26T17:14:30Z"
    mac: ENC[AES256_GCM,data:dZK++3WXUVTZOt9vLPGpT7OsKrx3nhJc/TWmiHEKKR2PrY9uZTjPmi1HVBm9yAmXodJ2vXgVedAg11edYwcJP7CWciyTo/VAwwu/5vwxL0ULx3HtBEOV+bNtHTyNRcSz2IRCv7oADlVKm0s21ddvGNIJJ77RgmZfmS3bfWiLrJY=,iv:TOW+k0Dqiq1UeZwsTte47v9E+gU9Vkm4RkVdDNGg/6c=,tag:4Qz4EaVnXSilq3aodHmi5Q==,type:str]
    version: 3.13.3
