apiVersion: v1
kind: Secret
metadata:
    name: loki-secrets
stringData:
    LOKI_SECRET_KEY: ENC[AES256_GCM,data:6rKNYu8o+lkp6sqyB4NVMUVi1uwFa8RlTdT42osFwFQkP7DysXadMh2Q85P79tnn2BiSIzLJNAGSfPRqK+ZZmA==,iv:KLkJMD2RMWDCjhJ7zMUpih90602mkzm6pHF68QaNkao=,tag:3mtAP0QqcKTXadtfF9EBfg==,type:str]
    LOKI_ACCESS_KEY: ENC[AES256_GCM,data:oqr6gl8aMRBPaCAi9913fhF7l3AMeTpvOBM=,iv:VOVFePdV8Sv9jwzBQ/7s4fjyRep2ghHW459JAYgsmaw=,tag:Pg+dCN1quQ9m5uA9hIovnA==,type:str]
sops:
    age:
        - recipient: age1yubikey1qdmjd6g9zxszvw332nlw8898pl9q8tnpjv8ljjvxpau650567j5a6nlpjz8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEcvTERKZyBBdXNBUURK
            dGFGSG5hZGx5c1pxRzZ1a3VaUWtoRXhVTWlTQjlJOVA4N0dYWgp5OTZYQzRTbmt0
            bTg3ZWhGcG1sTGlwM29WYVk2T1VUa0FiWUJLaElrYjZFCi0tLSBOQlZaS3J0bnRu
            djM2QXpYUHpPRE9YMkNJSmZSTHBkZjNKSXFJbGdTUk1vCgQZvMYjwZtg/jwusDAD
            BG9fH1ETDXP99plENYGPFHyJsy0hWpI/16h/16CH6y8M3QMx6Bu8Nx6ctx5ba85T
            WcA=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1qwu0zwltgvjgv7tr0qcpjw6grreja8lqwpsxdprgwyap29mrkvx6j6795r0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IE1TL0VLZyBBd2tWRllP
            cEc0L0sxZnQyTGYzMkUxbU5DNDNvSkM3cmxCaHMzT0dlVzR1Nwp5dG1FRXBTc2k2
            eW1RVEYzUFlmMm9EbW9iL2FqS0NOaXh6MlVCMlpnMkxzCi0tLSBiaDQrcFhMV1dx
            YUEvaHIyQmZxelB2dTNneUpXNHpvNnl1ejR3dkJQK0dNClObpT6h6hOVzLMbI65L
            PrHSM03ISCVOQm3UwlPuRbWxN9fGZcMnYfks7TZD7eB1GAR2LjgbEAOdKjDuJdpj
            PfI=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1qx0rq7nr30zw7kjhlh5nccfj8w30hdnlc890c6hqxqack5eayevqm8wp8m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4NXptTnU5VU1sdHQzVEQ2
            dFNkTTJ6dFo1Qy9LTnliR1B6d2pka210M2swClJFVmhqMkw1YUJxM0R1TTYwUWJp
            cmJ0TVNqRWxZWFNMMUxLOHJhR2hCMkUKLS0tIDFHb2d1bldyWUVwSkFhTElKZjJV
            SUFWdTNweE8yNXJVZkJ6Z1BBNTVBOTAKWMXVQ8bLnA2Qa1CKAT4CqbaZ8bOtLfPK
            J6iJJHoQgEMJaB1cqLJOzfLGM7iiEDnlTcTSdqbtAsYbo2sBpHb6XA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-24T19:26:09Z"
    mac: ENC[AES256_GCM,data:3HdyCndQQn95JrfoIihGG1f6wBmAS4ZpkUmVxAwzOGJDphtuOupBjHSXzUxblQqis+fGwLdxHvnJYIGtxUp98FkhraGLzwp2Y0rvopV0RQgF4KDLFAbQDN+enNT/8tKFmBZLkq1bCw7SqK1oCrWZs2d6r4ZEOn+rIgoLSY32m2k=,iv:bL7lKH//bU2i6Cg4r7Cf2SymgBvuJ5+dX5lGt7hoTU0=,tag:27xpLlg1lN0LsLR8bC7vyA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
